version: '3.4'

x-common-variables: &common-variables
  HSELING_RPC_ENDPOINT: http://hse-api-web:80/rpc/
  HSELING_API_ENDPOINT: http://hse-api-web:80/api/
  RESTRICTED_MODE: 0

services:
  hse-api-web:
    build:
      context: .
      dockerfile: hseling-api-poem-generator/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - type: bind
        source: ./hseling-api-poem-generator/hseling_api_poem_generator
        target: /app/hseling_api_poem_generator
      - type: bind
        source: ./hseling-data-poem-generator/api
        target: /data
    environment: *common-variables






  hse-web-web:
    build:
      context: .
      dockerfile: hseling-web-poem-generator/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - hse-api-web
    environment: *common-variables
    volumes:
      - type: bind
        source: ./hseling-web-poem-generator/hseling_web_poem_generator
        target: /app/hseling_web_poem_generator
      - type: bind
        source: ./hseling-web-poem-generator/hseling_web_poem_generator/static
        target: /app/static
      - type: bind
        source: ./hseling-data-poem-generator/web
        target: /data
